[2022-02-18 03:20:26,497] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dev_to_staging.copy_to_staging manual__2022-02-18T03:20:23.874143+00:00 [queued]>
[2022-02-18 03:20:26,527] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dev_to_staging.copy_to_staging manual__2022-02-18T03:20:23.874143+00:00 [queued]>
[2022-02-18 03:20:26,529] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-18 03:20:26,530] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-18 03:20:26,531] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-18 03:20:26,541] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): copy_to_staging> on 2022-02-18 03:20:23.874143+00:00
[2022-02-18 03:20:26,550] {standard_task_runner.py:52} INFO - Started process 565 to run task
[2022-02-18 03:20:26,573] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dev_to_staging', 'copy_to_staging', 'manual__2022-02-18T03:20:23.874143+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/dev_to_staging.py', '--cfg-path', '/tmp/tmpwguubz1z', '--error-file', '/tmp/tmp39_iycpp']
[2022-02-18 03:20:26,575] {standard_task_runner.py:77} INFO - Job 41: Subtask copy_to_staging
[2022-02-18 03:20:26,717] {logging_mixin.py:109} INFO - Running <TaskInstance: dev_to_staging.copy_to_staging manual__2022-02-18T03:20:23.874143+00:00 [running]> on host 51f5c68c784a
[2022-02-18 03:20:26,812] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dev_to_staging
AIRFLOW_CTX_TASK_ID=copy_to_staging
AIRFLOW_CTX_EXECUTION_DATE=2022-02-18T03:20:23.874143+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-18T03:20:23.874143+00:00
[2022-02-18 03:20:26,814] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: copy_to_staging() missing 1 required positional argument: 'temp_file_name'
[2022-02-18 03:20:26,841] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=dev_to_staging, task_id=copy_to_staging, execution_date=20220218T032023, start_date=20220218T032026, end_date=20220218T032026
[2022-02-18 03:20:26,877] {standard_task_runner.py:92} ERROR - Failed to execute job 41 for task copy_to_staging
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: copy_to_staging() missing 1 required positional argument: 'temp_file_name'
[2022-02-18 03:20:26,909] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-18 03:20:26,973] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
