[2022-02-17 23:42:23,228] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_staging_data_dag.get_all_dev_users manual__2022-02-17T23:41:47.162092+00:00 [None]>
[2022-02-17 23:42:23,230] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_staging_data_dag.get_all_dev_users manual__2022-02-17T23:41:47.162092+00:00 [None]>
[2022-02-17 23:42:23,232] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-17 23:42:23,233] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-17 23:42:23,234] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-17 23:42:23,261] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): get_all_dev_users> on 2022-02-17 23:41:47.162092+00:00
[2022-02-17 23:42:23,277] {standard_task_runner.py:52} INFO - Started process 6012 to run task
[2022-02-17 23:42:23,290] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_staging_data_dag', 'get_all_dev_users', 'manual__2022-02-17T23:41:47.162092+00:00', '--job-id', '32', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/create_staging_table.py', '--cfg-path', '/tmp/tmp0aoqudup', '--error-file', '/tmp/tmp9xoyt0n1']
[2022-02-17 23:42:23,301] {standard_task_runner.py:77} INFO - Job 32: Subtask get_all_dev_users
[2022-02-17 23:42:23,424] {logging_mixin.py:109} INFO - Running <TaskInstance: load_staging_data_dag.get_all_dev_users manual__2022-02-17T23:41:47.162092+00:00 [running]> on host bd44ee7f0b09
[2022-02-17 23:42:23,525] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_staging_data_dag
AIRFLOW_CTX_TASK_ID=get_all_dev_users
AIRFLOW_CTX_EXECUTION_DATE=2022-02-17T23:41:47.162092+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-17T23:41:47.162092+00:00
[2022-02-17 23:42:23,539] {base.py:79} INFO - Using connection to: id: dev. Host: 172.17.0.2, Port: 5432, Schema: public, Login: postgres, Password: ***, extra: {}
[2022-02-17 23:43:59,651] {local_task_job.py:212} WARNING - State of this instance has been externally set to upstream_failed. Terminating instance.
[2022-02-17 23:43:59,671] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 6012. PIDs of all processes in the group: [6012]
[2022-02-17 23:43:59,674] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 6012
[2022-02-17 23:44:31,798] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-02-17 23:44:31,880] {process_utils.py:70} INFO - Process psutil.Process(pid=6012, status='terminated', exitcode=0, started='23:42:22') (6012) terminated with exit code 0
